---

- hosts: all
  become: true
  tasks:
  
  - name: install apache packge and php support
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
